/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormPendaftaran extends javax.swing.JFrame {
    

    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
        
    namaField.putClientProperty("JTextField.placeholderText", "Nama lengkap"); 
    npmField.putClientProperty("JTextField.placeholderText", "Contoh: 2410010001"); 
    getRootPane().setDefaultButton(daftarButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminGroup = new javax.swing.ButtonGroup();
        namaLabel = new java.awt.Label();
        npmLabel = new java.awt.Label();
        prodiLabel = new java.awt.Label();
        jenisKelaminLabel = new java.awt.Label();
        minatLabel = new java.awt.Label();
        prodiCombo = new javax.swing.JComboBox<>();
        lakiRadio = new javax.swing.JRadioButton();
        perempuanRadio = new javax.swing.JRadioButton();
        javaCheck = new javax.swing.JCheckBox();
        pythonCheck = new javax.swing.JCheckBox();
        webCheck = new javax.swing.JCheckBox();
        temaToggle = new javax.swing.JToggleButton();
        daftarButton = new javax.swing.JButton();
        namaField = new javax.swing.JTextField();
        npmField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pendaftaran Workshop");

        namaLabel.setName("namaLabel"); // NOI18N
        namaLabel.setText("Nama");

        npmLabel.setName("npmLabel"); // NOI18N
        npmLabel.setText("NPM");

        prodiLabel.setName("prodiLabel"); // NOI18N
        prodiLabel.setText("Program Studi");

        jenisKelaminLabel.setName("jeniskelaminLabel"); // NOI18N
        jenisKelaminLabel.setText("Jenis Kelamin");

        minatLabel.setName("minatLabel"); // NOI18N
        minatLabel.setText("Minat");

        prodiCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Manajemen Informatika" }));
        prodiCombo.setName("prodiCombo"); // NOI18N

        jenisKelaminGroup.add(lakiRadio);
        lakiRadio.setSelected(true);
        lakiRadio.setText("Laki Laki");
        lakiRadio.setName("lakiRadio"); // NOI18N

        jenisKelaminGroup.add(perempuanRadio);
        perempuanRadio.setText("Perempuan");
        perempuanRadio.setName("perempuanRadio"); // NOI18N
        perempuanRadio.addActionListener(this::perempuanRadioActionPerformed);

        javaCheck.setText("Java");
        javaCheck.setName("javaCheck"); // NOI18N

        pythonCheck.setText("Python");
        pythonCheck.setName("pythonCheck"); // NOI18N

        webCheck.setText("Web");
        webCheck.setName("webCheck"); // NOI18N

        temaToggle.setText("Mode Gelap");
        temaToggle.setName("temaToggle"); // NOI18N
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        daftarButton.setText("Daftar");
        daftarButton.setName("daftarButton"); // NOI18N
        daftarButton.addActionListener(this::daftarButtonActionPerformed);

        namaField.addActionListener(this::namaFieldActionPerformed);

        npmField.addActionListener(this::npmFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisKelaminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lakiRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(perempuanRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(javaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pythonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daftarButton)
                            .addComponent(webCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(npmField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(192, 192, 192))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(npmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisKelaminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lakiRadio)
                        .addComponent(perempuanRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(javaCheck)
                        .addComponent(pythonCheck)
                        .addComponent(webCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarButton)
                    .addComponent(temaToggle))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
       //GEN-FIRST:event_temaToggleActionPerformed 
           gantiTema(temaToggle.isSelected()); 

    }//GEN-LAST:event_temaToggleActionPerformed
        //GEN-LAST:event_temaToggleActionPerformed
    
    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt)
     {//GEN-FIRST:event_daftarButtonActionPerformed
     
     //GEN-FIRST:event_daftarButtonActionPerformed 
         
     tampilkanRingkasan();
 
     }//GEN-LAST:event_daftarButtonActionPerformed
     //GEN-LAST:event_daftarButtonActionPerformed
    
    private void npmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npmFieldActionPerformed

    private void perempuanRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        tampilkanRingkasan();
    }//GEN-LAST:event_namaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Blok Nimbus buatan NetBeans diganti dengan tema FlatLaf 
        FlatLightLaf.setup(); 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarButton;
    private javax.swing.JCheckBox javaCheck;
    private javax.swing.ButtonGroup jenisKelaminGroup;
    private java.awt.Label jenisKelaminLabel;
    private javax.swing.JRadioButton lakiRadio;
    private java.awt.Label minatLabel;
    private javax.swing.JTextField namaField;
    private java.awt.Label namaLabel;
    private javax.swing.JTextField npmField;
    private java.awt.Label npmLabel;
    private javax.swing.JRadioButton perempuanRadio;
    private javax.swing.JComboBox<String> prodiCombo;
    private java.awt.Label prodiLabel;
    private javax.swing.JCheckBox pythonCheck;
    private javax.swing.JToggleButton temaToggle;
    private javax.swing.JCheckBox webCheck;
    // End of variables declaration//GEN-END:variables

    private void gantiTema(boolean gelap) {
       if (gelap) { 
        FlatDarkLaf.setup(); 
    } else { 
        FlatLightLaf.setup(); 
    } 
    FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka 
    temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");    
    }

    private void tampilkanRingkasan() {
         String jenisKelamin = lakiRadio.isSelected() ? "Laki-laki" : "Perempuan"; 
  
    List<String> minat = new ArrayList<>(); 
    for (JCheckBox cb : List.of(javaCheck, pythonCheck, webCheck)) { 
        if (cb.isSelected()) { 
            minat.add(cb.getText()); 
        } 
    } 
  
    String pesan = "Nama: " + namaField.getText() 
            + "\nNPM: " + npmField.getText() 
            + "\nProgram Studi: " + prodiCombo.getSelectedItem() 
            + "\nJenis Kelamin: " + jenisKelamin 
            + "\nMinat: " + (minat.isEmpty() ? "-" : String.join(", ", minat)); 
  
    JOptionPane.showMessageDialog(this, pesan, "Data Pendaftaran", 
            JOptionPane.INFORMATION_MESSAGE); 
    }
    
      
    
}
