/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        textNama.putClientProperty("JTextField.placeholderText", "Nama sesuai KTP");
        textNoHP.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");
        getRootPane().setDefaultButton(buttonPesan);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKelas = new javax.swing.ButtonGroup();
        labelNama = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        labelNoHP = new javax.swing.JLabel();
        textNoHP = new javax.swing.JTextField();
        labelKota = new javax.swing.JLabel();
        comboBoxKota = new javax.swing.JComboBox<>();
        labelKelas = new javax.swing.JLabel();
        radioButtonEkonomi = new javax.swing.JRadioButton();
        radioButtonBisnis = new javax.swing.JRadioButton();
        radioButtonEksekutif = new javax.swing.JRadioButton();
        labelFasilitas = new javax.swing.JLabel();
        checkBoxBagasi = new javax.swing.JCheckBox();
        checkBoxMakan = new javax.swing.JCheckBox();
        checkBoxAsuransi = new javax.swing.JCheckBox();
        labelCatatan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCatatan = new javax.swing.JTextArea();
        buttonPesan = new javax.swing.JButton();
        toggleButtonModeGelap = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNama.setText("Nama Pemesan");

        labelNoHP.setText("Nomor HP");

        textNoHP.addActionListener(this::textNoHPActionPerformed);

        labelKota.setText("Kota Tujuan ");

        comboBoxKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        labelKelas.setText("Kelas");

        buttonGroupKelas.add(radioButtonEkonomi);
        radioButtonEkonomi.setSelected(true);
        radioButtonEkonomi.setText("Ekonomi");

        buttonGroupKelas.add(radioButtonBisnis);
        radioButtonBisnis.setText("Bisnis");

        buttonGroupKelas.add(radioButtonEksekutif);
        radioButtonEksekutif.setText("Eksekutif");

        labelFasilitas.setText("Fasilitas Tambahan");

        checkBoxBagasi.setText("Bagasi");

        checkBoxMakan.setText("Makan");
        checkBoxMakan.addActionListener(this::checkBoxMakanActionPerformed);

        checkBoxAsuransi.setText("Asuransi");
        checkBoxAsuransi.addActionListener(this::checkBoxAsuransiActionPerformed);

        labelCatatan.setText("Catatan");

        textAreaCatatan.setColumns(20);
        textAreaCatatan.setRows(3);
        jScrollPane1.setViewportView(textAreaCatatan);

        buttonPesan.setText("Pesan");
        buttonPesan.addActionListener(this::buttonPesanActionPerformed);

        toggleButtonModeGelap.setText("Mode Gelap");
        toggleButtonModeGelap.addActionListener(this::toggleButtonModeGelapActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama)
                    .addComponent(labelNoHP))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNoHP)
                        .addGap(6, 6, 6))
                    .addComponent(textNama))
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(toggleButtonModeGelap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKota)
                            .addComponent(labelKelas)
                            .addComponent(labelFasilitas)
                            .addComponent(labelCatatan))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxKota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(154, 154, 154))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButtonEkonomi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(14, 14, 14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkBoxBagasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButtonBisnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkBoxMakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkBoxAsuransi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButtonEksekutif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(14, 14, 14)))))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(buttonPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoHP)
                    .addComponent(textNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKota)
                    .addComponent(comboBoxKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelKelas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonEkonomi)
                        .addComponent(radioButtonBisnis)
                        .addComponent(radioButtonEksekutif)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFasilitas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkBoxBagasi)
                        .addComponent(checkBoxMakan)
                        .addComponent(checkBoxAsuransi)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelCatatan))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPesan)
                    .addComponent(toggleButtonModeGelap))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNoHPActionPerformed

    private void checkBoxMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMakanActionPerformed

    private void checkBoxAsuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAsuransiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAsuransiActionPerformed

    private void toggleButtonModeGelapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonModeGelapActionPerformed
        gantiTema(toggleButtonModeGelap.isSelected());
    }//GEN-LAST:event_toggleButtonModeGelapActionPerformed

    private void buttonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesanActionPerformed
       tampilkanRingkasan();
    }//GEN-LAST:event_buttonPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupKelas;
    private javax.swing.JButton buttonPesan;
    private javax.swing.JCheckBox checkBoxAsuransi;
    private javax.swing.JCheckBox checkBoxBagasi;
    private javax.swing.JCheckBox checkBoxMakan;
    private javax.swing.JComboBox<String> comboBoxKota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCatatan;
    private javax.swing.JLabel labelFasilitas;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelKota;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNoHP;
    private javax.swing.JRadioButton radioButtonBisnis;
    private javax.swing.JRadioButton radioButtonEkonomi;
    private javax.swing.JRadioButton radioButtonEksekutif;
    private javax.swing.JTextArea textAreaCatatan;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNoHP;
    private javax.swing.JToggleButton toggleButtonModeGelap;
    // End of variables declaration//GEN-END:variables

    private void gantiTema(boolean gelap) {
      if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }
        FlatLaf.updateUI(); 
        toggleButtonModeGelap.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }

   private void tampilkanRingkasan() {
        String jenisKelas = "Ekonomi";
        if (radioButtonBisnis.isSelected()) {
            jenisKelas = "Bisnis";
        } else if (radioButtonEksekutif.isSelected()) {
            jenisKelas = "Eksekutif"; 
        }

        List<String> fasilitas = new ArrayList<>();
        for (JCheckBox cb : List.of(checkBoxBagasi, checkBoxMakan, checkBoxAsuransi)) {
            if (cb.isSelected()) {
                fasilitas.add(cb.getText());
            }
        }

        String pesan = "Nama Pemesan: " + textNama.getText()
                + "\nNomor HP: " + textNoHP.getText()
                + "\nKota Tujuan: " + comboBoxKota.getSelectedItem()
                + "\nKelas: " + jenisKelas
                + "\nFasilitas Tambahan: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
                + "\nCatatan: " + (textAreaCatatan.getText().isEmpty() ? "-" : textAreaCatatan.getText());

        JOptionPane.showMessageDialog(this, pesan, "Ringkasan Pemesanan",
                JOptionPane.INFORMATION_MESSAGE);
    }
}
